---
services:
  app:
    build: .
    environment:
      PHP_IDE_CONFIG: 'serverName=olvlvl-com'
      XDEBUG_MODE: develop
      ICANBOOGIE_INSTANCE: dev
      APP_MORE_METRICS: true
    ports:
      - '8010:80'
    volumes:
    - .:/app:delegated
    - ~/.composer:/root/.composer:delegated
    working_dir: /app
