---
version: "3.2"
services:
  app:
    build: .
    environment:
      PHP_IDE_CONFIG: 'serverName=olvlvl-com'
    ports:
      - '8010:80'
    volumes:
    - .:/app:delegated
    - ~/.composer:/root/.composer:delegated
    working_dir: /app
