<?php

namespace ICanBoogie;

/**
 * @var $article \App\Modules\Articles\Article
 */

?><div class="article-overview">
	<h3><a href="<?= $article->url ?>"><?= escape($article->title) ?></a></h3>

	<p class="article-meta text-muted">
		<a href="<?= $article->url('index') ?>">
			<time datetime="<?= $article->date->as_date ?>" class="article-time">
				<?= $article->date->format('F d, Y') ?>
			</time>
		</a>
	</p>

	<div class="article-excerpt"><?= $article->excerpt ?></div>
</div>
