<footer class="article-author">
	<h5 class="separator"><span>About the author</span></h5>
	<div class="article-author-body">
		<div><a href="/resume.html"><img src="/images/olvlvl-mini.avif" alt="Olivier Laviale" loading="lazy"/></a></div>
		<div class="article-author-text"><p style="margin-bottom: 0"><span class="distinct">Hi! I'm Olivier</span> 👋<br>You enjoyed the article and want to know more about me? Have a look at <a href="/resume.html">my resume</a>. You can also find me on <a href="https://github.com/olvlvl/">GitHub</a> and <a href="https://www.linkedin.com/in/olvlvl/">LinkedIn</a>.</p></div>
	</div>
</footer>
