<?php

namespace ICanBoogie;

use App\Modules\Articles\Article;

$muted ??= false;

/**
 * @var Article $this
 * @var bool $muted
 */

?><div class="article-overview <?= $muted ? "block-muted" : "" ?>">
	<h2><a href="<?= $this->url ?>"><?= $this->title ?></a></h2>

	<p class="article-meta text-muted">
		<a href="<?= $this->url('list') ?>">
			<time datetime="<?= $this->date->as_date ?>" class="article-time">
				<?= $this->date->format('F d, Y') ?>
			</time>
		</a>
	</p>

	<div class="article-excerpt"><?= $this->excerpt ?></div>
</div>
