<h1>Olivier Laviale
<small>On building software for internet</small></h1>
<?php

use App\Modules\Articles\Article;
use ICanBoogie\View\View;

/**
 * @var $this Article[]
 * @var $view View
 */

$anchor = null;

foreach ($this as $article) {
	$article_anchor = "$article->year-$article->month";

	if ($anchor !== $article_anchor) {
		$anchor = $article_anchor;

		?><a id="in-<?= $anchor ?>"></a><?php
	}

	echo $view->partial('articles/overview', $article);
}
