<?php

namespace App\Modules\Articles;

/**
 * @var $this Article
 * @var $continue_reading Article[]
 * @var $view \ICanBoogie\View\View
 */

?>

<section class="article-show">
	<div class="article-meta block-muted">
		<a href="/" class="article-author" rel="index">Olivier Laviale</a>
		—
		<a href="<?= $this->url('index') ?>" rel="index"><time class="article-time" datetime="<?= $this->date ?>"><?= $this->date->format('F d, Y') ?></time></a>
	</div>

	<div class="article-body"><?= $this->body ?></div>
</section>

<?php /*
<div class="article-comments">
	<?= $view->partial('disqus', [ 'article' => $this ]) ?>
</div> */ ?>

<footer class="article-continue">
<h5 class="separator"><span>Continue reading</span></h5>

<?php foreach ($continue_reading as $article): ?>
<?= $view->partial('articles/overview', [ 'article' => $article, 'muted' => true ]) ?>
<?php endforeach; ?>
</footer>
