<?php

namespace App\Modules\Articles;

/**
 * @var $this Article
 * @var $continue_reading Article[]
 * @var $view \ICanBoogie\View\View
 */

?>

<section class="article-show">
	<div class="article-meta">
		<a href="/" class="article-author" rel="index">Olivier Laviale</a>
		—
		<a href="<?= $this->url('index') ?>" rel="index"><time class="article-time"><?= $this->date->format('F d, Y') ?></time></a>
	</div>

	<div class="article-body"><?= $this->body ?></div>
</section>

<section class="article-comments">
	<?= $view->partial('disqus', [ 'article' => $this ]) ?>
</section>

<section class="article-continue">
	<h5 class="separator"><span>Continue reading</span></h5>

	<?php

	foreach ($continue_reading as $article)
	{
		echo $view->partial('articles/overview', [ 'article' => $article ]);
	}

	?>
</section>
