imports:
- { resource: services/*.yaml }

services:
  _defaults:
    autowire: true

  event.handler.before.article.action:
    class: App\Presentation\Handler\RoutingDispatcherDispatchHandler
    public: true

  event.handler.view.alter:
    class: App\Presentation\Handler\ViewAlterHandler
    public: true

  event.handler.not_found.rescue:
    class: App\Presentation\Handler\NotFoundRecoverHandler
    public: true

  event.handler.exception.rescue:
    class: App\Presentation\Handler\ExceptionRescueHandler
    public: true
