<?php

namespace ICanBoogie;

/**
 * @var $view \ICanBoogie\View\View
 * @var $content string
 * @var $page_title string
 */

$page_title = &$page_title;

?><!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title><?= $page_title ? $page_title . ' – ' : '' ?>olvlvl</title>

	<link type="text/css" rel="stylesheet" href="/assets/bootstrap.min.css" />
	<link type="text/css" rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.9.1/styles/github-gist.min.css" />
	<link type="text/css" rel="stylesheet" href="/assets/page.css" />
</head>
<body class="<?= $body_css ?>">
	<?php require '_navigation.phtml' ?>

	<div class="container">
		<?php if ($page_title): ?>
			<h1><?= $page_title ?></h1>
		<?php endif ?>
		<?= $content ?>
	</div>

	<?php require '_footer.phtml' ?>

	<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.9.1/highlight.min.js"></script>
	<script>hljs.initHighlightingOnLoad()</script>
	<script src="/assets/page.js"></script>
</body>
</html>
