<nav class="navbar">
	<span class="navbar-brand"><a href="/">Olivier Laviale</a> &bullet; <a href="https://twitter.com/olvlvl">@olvlvl</a></span>
	<ul class="nav navbar-nav pull-right">
		<li class="nav-item active">
			<a class="nav-link" href="/">Home</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="#">Archive</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="#">Tools</a>
		</li>
		<li class="nav-item">
			<a class="nav-link" href="https://github.com/olvlvl" target="_blank">GitHub</a>
		</li>
	</ul>
</nav>
