services:
  _defaults:
    autowire: true

  App\Modules\Articles\ArticleController:
    shared: false
    tags:
    - { name: action_responder }
    - { name: action_alias, action: 'articles:list' }
    - { name: action_alias, action: 'articles:show' }
    - { name: action_alias, action: 'articles:show_redirect' }
    - { name: action_alias, action: 'articles:feed' }

  App\Presentation\Controller\PageController:
    shared: false
    tags:
    - { name: action_responder }
    - { name: action_alias, action: 'pages:me' }
