services:
  _defaults:
    autowire: true
    public: true

  App\Presentation\Listener\RespondEventListener: ~
  App\Presentation\Listener\AlterViewListener: ~
  App\Presentation\Listener\RecoverNotFoundListener: ~
  App\Presentation\Listener\RecoverThrowableListener: ~
