<?php

namespace ICanBoogie;

/**
 * @var View\View $view
 * @var string $content
 * @var string [$page_title]
 * @var string $body_css
 * @var string [$og_description]
 */

if (empty($og_description))
{
	$og_description = "Olivier Laviale, on building software for internet";
}

?><!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="author" content="Olivier Laviale" />
	<meta name="description" content="<?= escape($og_description) ?>" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />

	<meta property="og:title" content="<?= empty($page_title) ? '' : escape($page_title) . ' — ' ?>Olivier Laviale" />
	<meta property="og:type" content="article" />
	<meta property="og:url" content="https://olvlvl.com<?= $og_url ?? '' ?>" />
	<meta property="og:image" content="https://olvlvl.com/images/olvlvl.jpg" />
	<meta property="og:image:width" content="512" />
	<meta property="og:image:height" content="512" />
	<meta property="og:description" content="<?= escape($og_description) ?>" />
	<meta property="og:locale" content="en_US" />

	<title><?= empty($page_title) ? '' : $page_title . ' – ' ?>Olivier Laviale</title>

	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@300&family=Roboto+Serif:ital,wdth,wght@0,90,300;1,90,300&family=Roboto+Serif:ital,wdth,wght@0,90,400;1,90,400&display=swap" rel="stylesheet">

	<link type="application/atom+xml" href="/index.atom" rel="alternate" title="Olivier Laviale" />
	<link type="text/css" rel="stylesheet" href="/assets/prism.css" />
	<link type="text/css" rel="stylesheet" href="/assets/page.css" />

	<script src="/assets/page.js"></script>
</head>
<body class="<?= $body_css ?>">
<div class="page-body">
	<?php if (isset($page_title)): ?>
		<h1><?= $page_title ?></h1>
	<?php endif ?>
	<?= $content ?>
</div>

<?php require '_footer.phtml' ?>
<?php require '_google_analytics.phtml' ?>
</body>
</html>
