<?php

/**
 * @var $article \App\Modules\Articles\Article
 */

?>
<div id="disqus_thread"></div>
<script>
	var disqus_config = function () {

		this.page.url = "http://olvlvl.com<?= $article->url ?>"
		this.page.identifier = "article-<?= $article->article_id ?>"

	};

	(function() {  // DON'T EDIT BELOW THIS LINE
		var d = document, s = d.createElement('script');

		s.src = '//olvlvl.disqus.com/embed.js';

		s.setAttribute('data-timestamp', +new Date());
		(d.head || d.body).appendChild(s);
	})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
