<footer class="page-footer">
	<div class="container">

		<span>Copyright © 2015-2017</span>
		<a href="/" rel="index">Articles</a>
		<a href="/about.html" rel="author">About</a>
		<a href="https://twitter.com/olvlvl" rel="external">@olvlvl</a>
		<a href="https://github.com/olvlvl" rel="external">GitHub</a>
		<a href="https://github.com/olvlvl/com.olvlvl.www" rel="external">Source code</a>

	</div>
</footer>
