parameters:
  modules.cache.enabled: false
  articles.minimum_visibility.show: !php/const \App\Modules\Articles\Article::VISIBILITY_PRIVATE
  articles.minimum_visibility.list: !php/const \App\Modules\Articles\Article::VISIBILITY_PRIVATE
