parameters:
  article_locations:
  - content/articles

  database_location: var/db.sqlite

services:
  _defaults:
    autowire: true

  App\Modules\Articles\ArticleImporter: ~

  App\Modules\Articles\ArticleSynchronizer:
    class: App\Modules\Articles\ArticleSynchronizerWithImporter
    lazy: true

  App\Modules\Articles\Listener\BeforeRespondEventListener:
    public: true

  App\Modules\Articles\Listener\StatementNotValidListener:
    public: true
