parameters:
  article_location: content/articles
  database_location: var/db.sqlite

services:
  _defaults:
    autowire: true

  App\Modules\Articles\ArticleImporter: ~

  App\Modules\Articles\ArticleSynchronizer:
    class: App\Modules\Articles\ArticleSynchronizerWithImporter
    lazy: true

  App\Modules\Articles\Listener\SynchronizeOnTheFly:
    public: true

  App\Modules\Articles\Listener\RecoverFromMissingTable:
    public: true

  # Console

  App\Modules\Articles\Console\ImportArticlesCommand:
    class: App\Modules\Articles\Console\ImportArticlesCommand
    tags:
      - { name: console.command }
