parameters:
  article_locations:
  - content/articles

  database_location: repository/db.sqlite

services:
  _defaults:
    autowire: true

  App\Modules\Articles\ArticleSynchronizer:
    class: App\Modules\Articles\ArticleSynchronizerWithImporter
    arguments:
      $article_locations: '%article_locations%'
    lazy: true

  App\Modules\Articles\Listener\BeforeControllerActionListener:
    arguments:
      $article_locations: '%article_locations%'
      $database_location: '%database_location%'
    public: true
    tags:
    - name: icanboogie.event
      sender: App\Modules\Articles\ArticleController
      event: ICanBoogie\Routing\Controller\BeforeActionEvent

  App\Modules\Articles\Listener\StatementNotValidListener:
    public: true
